version: '3'
services:
  express:
    container_name: express
    build: .
    command: ./wait-for.sh mysql-app:3306 -- yarn start
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MYSQL_DATABASE_HOST: mysql-app
      PG_DATABASE_HOST: postgres-app
    # volumes:
    # - ./:/src/
    depends_on:
      - mysql-app
      - postgres-app
    networks:
      - app-connect

  postgres-app:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - app-connect

  mysql-app:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/data
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-connect

volumes:
  mysql-data:
  postgres-data:

networks:
  app-connect:
    driver: bridge
