module.exports = [
  {
    name: 'mysql-connection',
    type: 'mysql',
    host: process.env.DATABASE_HOST_MYSQL,
    port: 3306,
    username: 'admin',
    password: 'admin',
    database: 'admin',
    synchronize: true,
    logging: true,
    entities: [`dist/src/entity/mysql/*.js`],
    migrations: ['src/migration/mysql/**/*.ts'],
    // subscribers: ['src/subscriber/**/*.ts'],
  },
  {
    name: 'postgresql-connection',
    type: 'postgres',
    host: process.env.DATABASE_HOST_PG,
    port: 5432,
    username: 'postgres',
    password: 'admin',
    database: 'dev',
    synchronize: true,
    logging: true,
    entities: [`dist/src/entity/pg/*.js`],
    migrations: ['src/migration/pg/**/*.ts'],
    // subscribers: ['src/subscriber/**/*.ts'],
  },
]
